### ISSUE TITLE
Clarify meaning of Network.startInviting() and Network.stopInviting()

### ISSUE THREAD

**Issue by cjdelisle** [coast-team/netflux#11]
It seems that a Network is a sort of multicast group within the overall network (since there is a Facade.onPeerMessage() I take it the Facade is really a network). I can see using an introducing server at the Facade level but I assume someone is not able to join a Network until they are reachable at the Facade level and so they have already been introduced. Perhaps I am not understanding the meaning of `Network.startInviting()` properly.

**Comment by kalitine** [comment]
You may think of any `Facade` attributes starting by `on` as the API configuration. Most of them has `Network` in parameter to know on which network it occurs.

`Network.startInviting()` has come from webRTC thinking way. By this I mean the following: 
in order to establish a connection between two peers (two browsers) we need a help of a signaling server. Thus when this method is invoked, behind the scene there is webSocket connection establishment with signaling server and the method returns something like `http://mysignalingserver.io/MySuperSecretPassword` which you give to another peer (send by email for example). The second peer put this URL into `Facade.join()` and again behind the scene there is webSocket with signaling server (that means that anyone who has this URL can establish peer to peer connection with you).

Then `Network.stopInviting()` closes webSocket with signaling server and thus nobody can establish peer to peer connection with you.

**Comment by cjdelisle** [comment]
Ok but the problem is that in the context of a WebSocket or other transport, this will make no sense at all. Perhaps we could use `WebRTCNetflux.create(String introductionServer) -> Facade` and then Facade does not need to have implementation details. In this case the WebSocket equivalent would be `WebSocketNetflux.create(String websocketURL) -> Facade`.
WDYT?

**Comment by kalitine** [comment]
I see and agree that from WebSocket or other possible transport point of view this approach does not suit.

Indeed when working on API we mostly focused on WebRTC, but also considered WebSocket alternative and also a mix of WebRTC and WebSocket (maybe too greedy, but still dreaming :)). We see WebSocket implementation as a gray module (if you look at UML diagram) together with `WebRTCService`. That means that `Network.startInviting()` and `Network.stopInviting()` methods should not be in `Network`, but somehow in `WebRTCService`. So this point need to be redone differently in the current state of the API.

In your suggestion (about `WebRTCNetflux` and `WebSocketNetflux`) the `create` method returns different `Facade` right? So the API user should use between WebSocket or WebRTC at the beggining. I am not sure I understood well.

**Comment by kalitine** [comment]
`startInviting` is now [`WebChannel.open`](https://doc.esdoc.org/github.com/coast-team/netflux/class/src/WebChannel.js~WebChannel.html#instance-method-open)
`stopInviting` is now [`WebChannel.close`](https://doc.esdoc.org/github.com/coast-team/netflux/class/src/WebChannel.js~WebChannel.html#instance-method-close)

You may find a usage example here: https://doc.esdoc.org/github.com/coast-team/netflux/manual/example.html
