### ISSUE TITLE
WASM

### ISSUE THREAD

**Issue by hybrisCole** [coast-team/netflux#148]
would it be any advantage in using this along with WASM?

**Comment by kalitine** [comment]
I do not think so. At least not very big because there is no hard computations here. The complexity is in the architecture and distributed algorithms who manage network topology structure and connection establishment.

I would say that there is only one thing we may think about and is the message protocol. Netflux uses Protocol Buffer ([protobuf.js library](https://github.com/dcodeIO/ProtoBuf.js/)) as a transport format for all messages. The library's author claims that `protobuf.js` is faster than JSON stringify/parse (which is native code), but still all message construction/parsing is done in JS. It make sense to think that we may get a performance gain would it be in wasm.
